Use one retry only
Signed-off-by: Antonio Gamez Diaz <antonio.gamez@suse.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -438,7 +438,12 @@ jobs:
           MIX_ENV: test
         run: |
           mix coveralls.json --warnings-as-errors --trace || \
-            if [[ $? = 2 ]]; then mix coveralls.json --warnings-as-errors --trace --failed; else false; fi
+            if [[ $? = 2 ]]; then
+              echo "::warning::Backend tests failed, retrying previously failed tests..."
+              mix test --trace --failed
+            else
+              false
+            fi
       - name: Upload coverage to Coveralls
         continue-on-error: true
         uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2
@@ -686,7 +691,7 @@ jobs:
         with:
           working-directory: test/e2e
           wait-on-timeout: 30
-          config: baseUrl=http://localhost:4000,retries=2
+          config: baseUrl=http://localhost:4000,retries=1
           expose: photofinish_binary=${{ steps.photofinish-path.outputs.path }}
       - name: Upload cypress test screenshots
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
@@ -798,7 +803,7 @@ jobs:
           working-directory: test/e2e
           spec: ${{ matrix.cypress_spec }}
           wait-on-timeout: 30
-          config: baseUrl=http://localhost:4000,retries=2
+          config: baseUrl=http://localhost:4000,retries=1
           expose: photofinish_binary=${{ steps.photofinish-path.outputs.path }}
       - name: Upload cypress test screenshots
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
@@ -948,7 +953,7 @@ jobs:
           working-directory: test/e2e
           spec: ${{ matrix.cypress_spec }}
           wait-on-timeout: 30
-          config: baseUrl=http://localhost:4000,retries=2
+          config: baseUrl=http://localhost:4000,retries=1
           expose: photofinish_binary=${{ steps.photofinish-path.outputs.path }},${{ matrix.cypress_expose }}
       - name: Upload cypress test screenshots
         uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
