Improve flaky tests e2e summary (#3718)
* test new summary

* show failure rate and fix quantity of flaky tests

* fix

* fix unique flaky tests and leave only percentage

* fix unique flaky tests and leave only percentage

* remove failing test

diff --git a/.github/workflows/e2e-flaky-tests-detection.yaml b/.github/workflows/e2e-flaky-tests-detection.yaml
--- a/.github/workflows/e2e-flaky-tests-detection.yaml
+++ b/.github/workflows/e2e-flaky-tests-detection.yaml
@@ -231,12 +231,48 @@ jobs:
           path: junit-reports
           pattern: e2e-junit-reports-*
           merge-multiple: true
-      - name: Analyze
+      - name: Analyze Flaky Tests and Generate Summary
+        id: analyze
+        env:
+          TOTAL_CONTAINERS: ${{ github.event.inputs.num_containers || env.DEFAULT_NUM_CONTAINERS }}
         run: |
+          REPORTS_PATH="../../junit-reports"
+          TOTAL_CONTAINERS=${{ env.TOTAL_CONTAINERS }}
+          
+          FAILED_RUNS=$(grep -l -E "<failure|<error>" $REPORTS_PATH/*.xml 2>/dev/null | wc -l)
+
+          if [ "$TOTAL_CONTAINERS" -gt 0 ]; then
+            FAILURE_PERCENTAGE=$(echo "scale=1; $FAILED_RUNS * 100 / $TOTAL_CONTAINERS" | bc)
+          else
+            FAILURE_PERCENTAGE=0
+          fi
+          
+          echo "### 📊 Suite Stability Summary" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "**Failure rate:** (Failing threads / Total threads) **${FAILURE_PERCENTAGE}%**" >> $GITHUB_STEP_SUMMARY
+          
           make venv-create
           source .venv/bin/activate
           make install-deps
-          make PATH-TO-JUNIT-FILES=../../junit-reports analyze-files 2>&1 | tail -n +2 >> $GITHUB_STEP_SUMMARY
+
+          FLAKY_TEST_LIST=$(make PATH-TO-JUNIT-FILES=$REPORTS_PATH analyze-files 2>&1 | tail -n +2)
+
+          NUM_FLAKY_TESTS=$(( $(echo -n "$FLAKY_TEST_LIST" | grep -c . || true) - 1 ))
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "---" >> $GITHUB_STEP_SUMMARY
+          echo "### Flaky Tests Analysis" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "**Unique flaky tests reported:** **$NUM_FLAKY_TESTS**" >> $GITHUB_STEP_SUMMARY
+          echo "" >> $GITHUB_STEP_SUMMARY
+
+          if [ "$NUM_FLAKY_TESTS" -gt 0 ]; then
+            echo "<details><summary>Click to see the full list of flaky tests</summary>" >> $GITHUB_STEP_SUMMARY
+            echo "" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "$FLAKY_TEST_LIST" >> $GITHUB_STEP_SUMMARY
+            echo '```' >> $GITHUB_STEP_SUMMARY
+            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          fi
         working-directory: hack/flaky_tests_analysis
       - name: Delete Artifacts
         uses: geekyeggo/delete-artifact@v5
